### ISSUE TITLE
Hallo Theo

### ISSUE THREAD

**Issue by Saschko2000** [theo222/lazarus-thumbviewer#1]
Ich habe mich die letzte Woche sehr intensiv mit deinem Thumbviewer auseinandergesetzt.
Echt klasse umgesetzt. Erstmal danke dafür.

Ich habe zwei kleine Fehler gefunden, die ich dir mitteilen wollte.

Ich habe außerdem einige Erweiterungen dazugefügt (Ownerdraw Caption with CaptionHeight / Multiselect / Drag  and Drop / ThumbFrameWith )

evtl. hast du ja interesse einiges zu übernehmen.

Wir könnten ja mal darüber reden. Ist wahrscheinlich einfacher als wenn du dir den ganzen kram alleine durchschaust.

Lieben Gruß

```
   Sascha
```

**Comment by theo222** [comment]
Hallo Sascha

Mach einfach, ich hab dich mal als Collaborator auf GitHub hinzugefügt. (Keine Ahnung ob das reicht, hab ich noch nie gemacht. Sonst sag mir, was ich tun muss).
Liebe GrüßeTheo

```
  Von: Saschko2000 <notifications@github.com>
```

 An: theo222/lazarus-thumbviewer lazarus-thumbviewer@noreply.github.com 
 Gesendet: 15:18 Dienstag, 17.Februar 2015
 Betreff: [lazarus-thumbviewer] Hallo Theo (#1)

Ich habe mich die letzte Woche sehr intensiv mit deinem Thumbviewer auseinandergesetzt.
Echt klasse umgesetzt. Erstmal danke dafür.Ich habe zwei kleine Fehler gefunden, die ich dir mitteilen wollte.Ich habe außerdem einige Erweiterungen dazugefügt (Ownerdraw Caption with CaptionHeight / Multiselect / Drag and Drop / ThumbFrameWith )evtl. hast du ja interesse einiges zu übernehmen.Wir könnten ja mal darüber reden. Ist wahrscheinlich einfacher als wenn du dir den ganzen kram alleine durchschaust.Lieben Gruß   Sascha

**Comment by theo222** [comment]
No response. Closing
