### ISSUE TITLE
Background color not changeable, Component not high-dpi aware, Warning about OffsetRect being deprecated

### ISSUE THREAD

**Issue by wp-xyz** [theo222/lazarus-thumbviewer#4]
Hi Theo
I found a few issues with your excellent thumbnail viewer:

* The background color of the control cannot be changed - there is a published `Color` property but changing it makes not difference. --> This is due to the `Paint()` method using hardcoded `clWhite` as background color.
* The component does not scale properly on high-dpi screens. The method `DoAutoAdjustLayout` should be added to scale the inner lengths used in the component; and there are some hard-coded constants which must be scaled on-the-fly.
* Recently the Lazarus team moved some functions to other units and deprecated the procedure `LCLIntf.OffsetRect` which will be in `types` in the future. To avoid possible compilation issues, the unit `types` should be moved after the unit `LCLIntf` in the `uses` clause.

I am attaching a patch which addresses these issues:

[color_highdpi_deprecated.patch](https://github.com/theo222/lazarus-thumbviewer/files/13326546/color_highdpi_deprecated.patch)

**Comment by theo222** [comment]
Hi! Thanks!
Just one question: Does this line make sense or is it a leftover from debugging?
`+  frame.saveToFile('framecropab.png');`

**Comment by wp-xyz** [comment]
Sorry, clearly a left-over from my experiments trying to understand why the slides had sharp corners after changing the background color. Please, remove it.

**Comment by theo222** [comment]
Your patch is applied.
I have not tested more than whether it compiles and runs.
I trust you that it makes sense.
Thank you!

**Comment by wp-xyz** [comment]
Thanks
