### ISSUE TITLE
loading another image instead of a thumbnail

### ISSUE THREAD

**Issue by Maxime349** [theo222/lazarus-thumbviewer#6]
Hi Theo and thank you for this great thumbviewer. 

I have 2 simple questions:
when I click on a thumbnail, I want to load another image (for example test.jpg) INSTEAD of the image I've clicked on.
For example if I click on the 3rd image of the 5th row, I want test.jpg to appear in that exact thumb (3rd image of the 5th row).

```
procedure TForm1.ThumbControl1SelectItem(Sender: TObject; Item: TThreadedImage);
begin
   Label1.Caption := ExtractFileName(ThumbControl1.ImageLoaderManager.ActiveItem.URL);
 
if Item <> nil then
  begin
 ???
  end;
end;
```

Second, what I would like to do is, with mouse enter and mouse leave, a cool animation effect and load a different 2nd thumbs of all my images.
Imagine I have a thumb of my holiday in London, I move the mouse ON and it start loading every second a different image from my London folder, same if I move on my holiday in Paris, it start loading images from my Paris folder etc... Maybe not 50 images but 3 or 4 different ones would be cool, like the default would be Paris0.jpg, I move my cursor on then I could load Paris1.jpg, after a second Paris2.jpg then repeat 0,1,2,0,1,2...   

```
procedure TForm1.ThumbControl1MouseMove(Sender: TObject; Shift: TShiftState; X,
  Y: Integer);
var itm:TThreadedImage;
begin
 itm:=ThumbControl1.ItemFromPoint(Point(x,y));
 
if assigned(itm) then begin Label1.Caption:=itm.URL; Screen.Cursor := crHandPoint; end else
 begin Label1.Caption:=''; Screen.Cursor := crDefault; end;
end;    
```

I can get the position, original image path, but I couldn't load another image...
many thanks in advance

**Comment by theo222** [comment]
I don't think that's what the thumbviever is designed for.
Feel free to do whatever you want with the code.
I won't change anything after 12 years, apart from compatibility adjustments if necessary.

**Comment by theo222** [comment]
Closing. Thank you!
